version: '3.8'

services:
  strapi:
    image: batclim_cms_image:latest
    container_name: batclim_cms
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/srv/app/.tmp
      - ./uploads:/srv/app/public/uploads
    ports:
      - "1337:1337"